name: news_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.3
  bloc: ^7.1.0
  rxdart: ^0.27.1
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.0
  carousel_slider: ^4.0.0
  timeago: ^3.1.0
  flutter_html: ^2.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12
  splashscreen: ^1.3.5
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/logoSplashScreen.png
  android: true
  ios: true


flutter:


  uses-material-design: true


  assets:
    - assets/img/loadingPlaceholder.gif
    - assets/img/placeholder.jpg
    - assets/logos/abc-news.png
    - assets/logos/al-jazeera-english.png
    - assets/logos/ars-technica.png
    - assets/logos/associated-press.png
    - assets/logos/axios.png
    - assets/logos/bbc-news.png
    - assets/logos/bbc-sport.png
    - assets/logos/bleacher-report.png
    - assets/logos/bloomberg.png
    - assets/logos/business-insider.png
    - assets/logos/buzzfeed.png
    - assets/logos/cbc-news.png
    - assets/logos/cbs-news.png
    - assets/logos/cnn.png
    - assets/logos/espn.png
    - assets/logos/financial-post.png
    - assets/logos/fortune.png
    - assets/logos/fox-news.png
    - assets/logos/fox-sports.png
    - assets/logos/google-news.png
    - assets/logos/hacker-news.png
    - assets/logos/ign.png
    - assets/logos/independent.png
    - assets/logos/mashable.png
    - assets/logos/msnbc.png
    - assets/logos/mtv-news.png
    - assets/logos/national-geographic.png
    - assets/logos/news24.png
    - assets/logos/politico.png
    - assets/logos/recode.png
    - assets/logos/reuters.png
    - assets/logos/rte.png
    - assets/logos/techcrunch.png
    - assets/logos/techradar.png
    - assets/logos/the-hill.png
    - assets/logos/the-huffington-post.png
    - assets/logos/the-next-web.png
    - assets/logos/the-wall-street-journal.png
    - assets/logos/the-washington-post.png
    - assets/logos/time.png
    - assets/logos/wired.png
    - assets/logos/breitbart-news.png
    - assets/logos/crypto-coins-news.png
    - assets/logos/engadget.png
    - assets/logos/entertainment-weekly.png
    - assets/logos/espn-cric-info.png
    - assets/logos/medical-news-today.png
    - assets/logos/national-review.png
    - assets/logos/nbc-news.png
    - assets/logos/new-scientist.png
    - assets/logos/newsweek.png
    - assets/logos/next-big-future.png
    - assets/logos/nfl-news.png
    - assets/logos/nhl-news.png
    - assets/logos/polygon.png
    - assets/logos/reddit-r-all.png
    - assets/logos/new-york-magazine.png
    - assets/logos/the-american-conservative.png
    - assets/logos/the-verge.png
    - assets/logos/the-washington-times.png
    - assets/logos/usa-today.png
    - assets/logos/vice-news.png
    - assets/logos/logo_placeholder.png



  #
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

